;;; vertigo-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vertigo.el

(autoload 'vertigo-jump-down "vertigo" "\
Jump down a number of lines using the home row keys." t)
(autoload 'vertigo-jump-up "vertigo" "\
Jump up a number of lines using the home row keys." t)
(autoload 'vertigo-visible-jump-down "vertigo" "\
Jump down a number of visible lines using the home row keys." t)
(autoload 'vertigo-visible-jump-up "vertigo" "\
Jump up a number of visible lines using the home row keys." t)
(autoload 'vertigo-visual-jump-down "vertigo" "\
Jump down a number of visual lines using the home row keys." t)
(autoload 'vertigo-visual-jump-up "vertigo" "\
Jump up a number of visual lines using the home row keys." t)
(autoload 'vertigo-set-digit-argument "vertigo" "\
Set a positive digit argument using vertigo keys.
If ARG is non-nil, set a negative count.

(fn ARG)" t)
(autoload 'vertigo-run-command-with-digit-argument "vertigo" "\
Like `vertigo-set-digit-argument', but the command is chosen first.
After keys have been pressed that correspond to a command, vertigo will prompt
to set the digit argument for that command and then run it.

(fn COMMAND-KEYS)" t)
(autoload 'vertigo-alt-run-command-with-digit-argument "vertigo" "\
Like `vertigo-run-command-with-digit-agument' but properly messages.
A message showing the command and the prefix arg will be displayed in the
echo area afterwards. M-[0-9] must be mapped to `digit-argument' for this
command to work correctly.

(fn COMMAND-KEYS)" t)
(autoload 'vertigo-set-negative-digit-argument "vertigo" "\
Set a negative digit argument using vertigo keys.
If ARG is non-nil, set a positive count.

(fn ARG)" t)
(register-definition-prefixes "vertigo" '("vertigo-"))

;;; End of scraped data

(provide 'vertigo-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vertigo-autoloads.el ends here
